### PR TITLE
Support Swift v4 in new branch

### PR DESCRIPTION
**Pull request by sjanuary**

### CODE REVIEW

**Comment by mattcolegate** [comment]
Is there no fancy 'Package@swift-4.0.swift' we can use?

**Comment by sjanuary** [comment]
@mattcolegate That doesn't seem to work any more.  The new way if you want to support 3.1 and 4 is to use `// swift-tools-version:3.1` and Swift 4 will build your package in compatability mode, but due to our unusual and specific build requirements SwiftMetrics doesn't actually build with Swift 4 in compatability mode even though it seems like it should.  https://github.com/apple/swift-evolution/blob/master/proposals/0152-package-manager-tools-version.md is useful reference.

**Comment by mattcolegate** [comment]
plus ça change, plus c'est la même chose

**Comment by sjanuary** [comment]
It seems like having a Package@swift-3.1.swift **should** work for building on Swift 3.1, but it doesn't, I get:
`error: Package requires minimum Swift tools version 4.0.0. Current Swift tools version is 3.1.0`.

**Comment by sjanuary** [comment]
Raised https://bugs.swift.org/browse/SR-5849 for current test failures (crash due to double free in omr-agentcore on Linux after building on Swift4)

**Review by mattcolegate — APPROVED** [review]
LGTM

**Pull request merged**
