### PR TITLE
refactoring divs

### PR DESCRIPTION
**Pull request by JulienArnold**
renaming divs to be easier to parse/test with selenium. Nothing major

### CODE REVIEW

**Comment by JulienArnold** [comment]
Should be ready to merge

**Review by mattcolegate — DISMISSED** [review]
You've added a lot of extra whitespace into the charts - extra spaces on the end of lines, blank lines containing tab or space characters. Can you please remove the extra whitespace and push that commit up, so that this PR only contains necessary changes?

**Comment by JulienArnold** [comment]
d3js has an inbuilt 'setInterval' function called d3.timer; same parameters - pass the process you want to run, and the time interval in ms. Much more efficient, less skipping and stop-starting than setInterval.

Should be ready to merge

**Comment by tobespc** [comment]
cancelling as no longer required

**Pull request closed without merging**
