### PR TITLE
fix issue#20 isAgentEnabled in AutoScalar should be able to be update…

### PR DESCRIPTION
**Pull request by qibobo**
…d to true if server config changes.

### CODE REVIEW

**Review by mattcolegate — DISMISSED** [review]
This change needs to be duplicated into the if block for 'poller' (it should be line 399).

**Comment by qibobo** [comment]
@mattcolegate For the agent, we should only care the agent config, if agent's config is nil , we should disable the agent and do not care the poller's.

**Comment by tobespc** [comment]
#20

**Comment by mattcolegate** [comment]
I believe we need to care about poller - here's the output from my test app log:

APP/0
[2017-02-17T10:43:38.250Z] [DEBUG] [SwiftMetricsBluemix.swift:371 refreshConfig()] [Auto-scaling Agent] Attempting requestConfig request to https://Scaling2.ng.bluemix.net:443/v1/agent/config/00b7ecc6-3a5f-454c-a231-d458c3614a5a/7b95965a-e618-4b01-aa48-d6d8ad255dcc?appType=swift
Feb 17, 2017 10:43:38 AM
APP/0
[2017-02-17T10:43:38.283Z] [DEBUG] [SwiftMetricsBluemix.swift:379 refreshConfig()] [Auto-scaling Agent] requestConfig:Data: 59 bytes
Feb 17, 2017 10:43:38 AM
APP/0
[2017-02-17T10:43:38.284Z] [DEBUG] [SwiftMetricsBluemix.swift:380 refreshConfig()] [Auto-scaling Agent] requestConfig:Error: nil
Feb 17, 2017 10:43:38 AM
APP/0
[2017-02-17T10:43:38.284Z] [DEBUG] [SwiftMetricsBluemix.swift:381 refreshConfig()] [Auto-scaling Agent] requestConfig:Body: Optional("{\"reportInterval\":30,\"metricsConfig\":{\"poller\":[\"Memory\"]}}")
Feb 17, 2017 10:43:38 AM
APP/0
[2017-02-17T10:43:38.285Z] [DEBUG] [SwiftMetricsBluemix.swift:389 updateConfiguration(response:)] [Auto-scaling Agent] attempting to update configuration with JSON(rawString: "", rawNumber: 0, rawNull: <NSNull: 0x0000000000c79710>, rawArray: [], rawDictionary: ["reportInterval": 30, "metricsConfig": ["poller": ["Memory"]]], rawBool: false, _type: SwiftyJSON.Type.dictionary, _error: nil)
Feb 17, 2017 10:43:38 AM
APP/0
[2017-02-17T10:43:38.286Z] [EXIT] [SwiftMetricsBluemix.swift:405 updateConfiguration(response:)] [Auto-scaling Agent] Updated configuration - enabled metrics: ["Memory"], report interval: 30 seconds

If we don't care about poller, then my app's agent configuration doesn't get updated.

**Comment by qibobo** [comment]
@mattcolegate This is because swift support is still not available on YP dallas. Now it is available on LYS1. And when it works, it will return agent configs.

**Pull request merged**
