### PR TITLE
Update swift-cfenv, 4.0.2 migration & remove KituraRequest & add SwiftyRequest

### PR DESCRIPTION
**Pull request by KyeMaloy97**
This fixes the generate swift-server issue where the packages wouldn't resolve due to package conflicts. Also have removed KituraRequest support in favor of SwiftyRequest as KituraRequest is no longer being updated. Removed character references for Swift 4.0.2.

### CODE REVIEW

**Comment by sjanuary** [comment]
@KyeMaloy97 has this been tested in Bluemix?

**Comment by sjanuary** [comment]
@KyeMaloy97 - this hasn't been merged, did you mean to close it? Is it not needed any more?

**Comment by KyeMaloy97** [comment]
I have no idea why it closed, it wasn't meant to be closed so I have reopened it. I will be updating the PR to tackle new parts of the original issue, mainly removing KituraRequest and using SwiftyRequest.

**Comment by KyeMaloy97** [comment]
Still using WebSocket 0.9.0 as using 1.0.0 causes the dependencies to no longer resolve.

**Comment by sjanuary** [comment]
This needs to be tested and reviewed by the BAM team to check the BAM data collector is still working the same as before.  I'm trying to find the right person to look at it, they don't seem to be taggable on GitHub at the moment...

@tobespc or @mattcolegate - could one of you also please write some instructions here on how @KyeMaloy97 can test that the data we send to the autoscaling service in Bluemix is still correct?

We don't yet have any automated tests for either SwiftMetricsBluemix or SwiftBAMDC so manual testing **must** be done for both before this PR can be merged.

**Comment by KyeMaloy97** [comment]
Closing. I will open separate PRs for the KituraRequest to SwiftyRequest and 4.0.2 migration changes.

**Comment by qiyaod** [comment]
My test failed and the build hang on -----> Fetching Swift packages and parsing Package.swift files...

Downloading swift_buildpack...
Downloaded swift_buildpack
Creating container
Downloading app package...
Successfully created container
Staging...
Downloaded app package (27.3K)
-----> Buildpack version 2.0.9
-----> Configure for apt-get installs...
-----> Default supported Swift version is 4.0.2
-----> Writing profile script...
-----> Copying deb files to installation folder...
-----> No Aptfile found.
-----> Getting swift-4.0.2
       Cached swift-4.0.2
-----> Unpacking swift-4.0.2.tar.gz
-----> Getting clang-4.0.0
       Cached clang-4.0.0
-----> Unpacking clang-4.0.0.tar.xz
-----> .ssh directory and config file not found.
-----> Skipping cache restore (new swift signature)
-----> Fetching Swift packages and parsing Package.swift files...

**Pull request closed without merging**
