### PR TITLE
 Remove JSON manipulation from SwiftMetricsDash Fixes #185

### LINKED ISSUE #185: Memory leak when using SwiftMetrics
When I include SwiftMetrics into my app as follows:

```swift
if let metrics = try? SwiftMetrics() {
    _ = try? SwiftMetricsDash(swiftMetricsInstance : metrics, endpoint: router)
}
```

my memory usage increases by about 50KB/s.

I am using SwiftMetrics 2.3 with Swift 4.1.2.

### PR DESCRIPTION
**Pull request by jonathan-spruce**
Removes the JSON used in the SwiftMetricsDash, which was causing a memory leak in Swift 4.1.2.

### CODE REVIEW

**Comment by seabaylea** [comment]
Rather than using using string templates, it would be much better (and safer!) to define Codable structs and then use the JSONEncoder from Foundation to create the payload, something like (not compiled!)

```swift
// Typesafe structs for CPU Data and wrapper object
struct CpuData: Codable {
    let process: Float
    let systemMean: Float
    let processMean: Float
    let time: Date
    let system: Float
}

struct Cpu: Codable {
    let topic = "cpu"
    let payload: Cpu
}

let cpu = Cpu(CpuData(.....))
let encoder = JSONEncoder()
let data = try encoder.encode(cpu)
```

**Comment by sjanuary** [comment]
@jonathan-spruce I actually did that work some time ago but it got taken out due to a clash with a more urgent piece of work. This might help you though: https://github.com/RuntimeTools/SwiftMetrics/pull/174/files

**Comment by jonathan-spruce** [comment]
There still seems to be a memory leak in the JSONEncoder, at least in the way I used it, so I have reverted back to the String implementation.

**Review by sjanuary — APPROVED** [review]

**Comment by sjanuary** [comment]
I would not normally merge a fix with a failing Travis build, but I can see that the master build started failing in the same way about 10 days ago and it's important that we get this memory leak fix in.  I will open another issue to investigate the test failures.

**Pull request merged**
