### PR TITLE
A few updates (mainly around CloudConfiguration).

### PR DESCRIPTION
**Pull request by rolivieri**
- Removed dependency on CloudConfiguration since that library is now deprecated.
- Updated version of swift to latest release (3.1.1).
- Updated package.pins (as a convention and following Apple's guidelines, Swift@IBM encourages using package.pins to specify specific versions only if the swift package is an application).
- Minor updates to README.

### CODE REVIEW

**Comment by sjanuary** [comment]
@rolivieri - our current policy is to support the latest release and the one before that (i.e. n and n-1).  So we still need to support 3.1.1 and 3.0.  In our last release we (incorrectly) used `Package.swift` as the manifest for Swift 3.0 and `Package@swift-3.1.swift` for 3.1.1.  If you have updated `Package.swift` to use the latest dependencies that work on Swift 3.1.1 then you need to delete `Package@swift-3.1.swift`, otherwise that will be picked up in preference.  Then you need to ensure that `Package.swift` works for 3.0 and if not then we'll need a `Package@swift-3.0.swift` to support Swift 3.0, which would essentially be a copy of the `Package.swift` that is now in master.  

The Travis config file `.travis.yml` also assumes that Swift 3.0 is the default, so if you edit `-swift-version` you also need to change `.travis.yml`.  As it stands if we accept this PR then Travis will run against Swift 3.1.1 twice for each platform instead of once on 3.1.1 and once on 3.0.

**Review by sjanuary — CHANGES_REQUESTED** [review]
Needs changes, as described in my comment.

**Comment by rolivieri** [comment]
@sjanuary Thanks for the review. I made the changes you requested above. If I missed anything, please let me know.

**Comment by sjanuary** [comment]
@rolivieri - The README change seems to remove information related to Swift 3.0, could you change that back to retain the 3.0 information please?  It can be under a separate header if you prefer so that we can remove it when we move on to supporting 4.0 and 3.1.1, which will be fairly soon.

We also need all 4 Travis builds to pass, only 1 seems to be passing currently.  Is `swift build` working for you on your machine with these latest changes? https://travis-ci.org/RuntimeTools/SwiftMetrics/jobs/272311079 looks suspiciously like it's stuck in the Swift Package Manager endless loop that can happen if it can't find compatible versions of all the dependencies in the tree.

**Comment by sjanuary** [comment]
@rolivieri Was `Package.resolved` checked in by accident?  Looks like the Xcode build is still failing on 3.0 but everything else is passing since your latest push.  Shouldn't it be `osx_image: xcode8.2` for 3.0 in travis.yml? Once the builds are green it just needs those README updates and `Package.resolved` removing and I'll be happy to merge.

**Comment by rolivieri** [comment]
@sjanuary Thanks for following up on this. I've been at a conference in NYC and haven't been able to focus on this PR as much as I intended. I apologize for my slowness. I am still working on it and hope to get all the builds passing soon.

**Comment by rolivieri** [comment]
@sjanuary I got the build for the PR to pass: https://travis-ci.org/RuntimeTools/SwiftMetrics/builds/273109908

**Comment by rolivieri** [comment]
@sjanuary - If I missed addressing any of the points you described above, please let know. I think they all have been addressed. Is there an ETA for merging this PR? Thanks!

**Comment by sjanuary** [comment]
@rolivieri I'm going to merge this today. Sorry for the delay, I don't work Fridays. 
FYI you can kick off a rebuild on Travis by opening the build job and clicking 'restart build', you don't need to make a minor doc update to do that.

**Review by sjanuary — APPROVED** [review]

**Pull request merged**
