### PR TITLE
Add SwiftMetricsPrometheus.swift to provide Prometheus support - Swift 4

### PR DESCRIPTION
**Pull request by hhellyer**
Add a Prometheus endpoint on /metrics to allow SwiftMetrics to be used with Prometheus.

This merges with the Swift 4 branch.

### CODE REVIEW

**Comment by sjanuary** [comment]
@hhellyer - could you add a short bit to the README please?

**Comment by NikCanvin** [comment]
Could the readme 'short bit', point to a BLOG 'longer bit', to join the dots?

**Comment by sjanuary** [comment]
@NikCanvin A longer bit sounds good and we should also consider whether our main landing page needs a refresh with this and Swift 4 support having been added recently.

**Review by sjanuary — APPROVED** [review]
Looks good, I've tested in general and opened the /metrics endpoint but not actually opened with Prometheus

**Pull request merged**
