### PR TITLE
Enable fullscreen graphs and support translation files

### PR DESCRIPTION
**Pull request by sjanuary**

### CODE REVIEW

**Comment by tobespc** [comment]
@sjanuary Sian, the graphmetrics submodule hash seems to be wrong.  I've redone the submodule to add the latest graphmetrics now I've pulled those changes in.  Can you rebase this changeset without graphmetrics change please

**Comment by sjanuary** [comment]
@tobespc I updated the submodule but the i18n change doesn't seem to have been ported to SwiftMetrics so the dashboard is completely broken... I've marked this PR as "DON'T MERGE" and I will port the changes across from appmetrics-dash.

**Comment by sjanuary** [comment]
Now includes i18n support

**Comment by sjanuary** [comment]
Rebased due to changes in master, superseded by #135

**Pull request closed without merging**
